# Generated by Django 2.2.28 on 2022-05-14 13:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplaces', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='opening_hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
