# Generated by Django 2.2.28 on 2022-05-15 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaces', '0004_auto_20220515_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
