# Generated by Django 2.2.28 on 2022-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaces', '0005_auto_20220515_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visited',
            name='visited_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
