# Generated by Django 2.2.28 on 2022-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaces', '0007_auto_20220515_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='street_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
