# Generated by Django 2.2.28 on 2022-05-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplaces', '0010_auto_20220516_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visited',
            options={'verbose_name_plural': 'Visited'},
        ),
    ]
