# Generated by Django 2.2.28 on 2022-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220605_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
